import { utilService } from './util-service.js'
import { storageService } from './async-storage-service.js'


const STORES_KEY = 'stores'
const gProducts =

{
    "Products": [
        {
            "ProductId": 206419,
            "ProductTitle": "Mom is Fabulous Fruit Box - Good",
            "Description": "A Jifiti gift will be received by the recipient as a virtual gift card which can be used to redeem the suggested gift or any other item at FTD\r\n\r\nProduct Description:\r\n\r\nMom is fabulous, so show her how much you care by sending this festive and fun gourmet fruit gift. Sure to please Mom on her special day!\nGOOD gift box holds fresh and juicy seasonal fruit, crackers, cheese, and almond tea cookies in a festive gift box.",
            "ProductImage": "http://www.ftdimg.com/pics/products/zoom/G144_600x600.jpg",
            "ThumbnailProductImage": null,
            "Price": 39.99,
            "PriceLabel": "$39.99",
            "ProductTags": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                28,
                29,
                30,
                31,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                90,
                91,
                92,
                93,
                96,
                97,
                98,
                99,
                100
            ],
            "IsTopGift": false,
            "IsPopularGift": false,
            "ProductLink": "http://www.ftd.com/all-mothers-day-pcg/mom-is-fabulous-fruit-box/occasion-mothersday-all/1g44/?sid=1",
            "IsAffiliate": false,
            "ShippingMandatory": true,
            "PersonalMessageMaxLength": null
        },
        {
            "ProductId": 205709,
            "ProductTitle": "Spring Sensation Fruit & Sweets Gourmet Gift Basket - GOOD",
            "Description": "A Jifiti gift will be received by the recipient as a virtual gift card which can be used to redeem the suggested gift or any other item at FTD\r\n\r\nProduct Description:\r\n\r\nThe Spring Sensation Fruit & Sweets Gourmet Gift Basket is an incredible array of gourmet goodies ready to make your special recipient's day one they won't soon forget! A beautiful natural woven basket with pink and green accents is tied with a pink ribbon.\nGOOD Basket includes 2 D'Anjou Pears, 1 Red Pear, 2 Braeburn Apples, 2 Navel Oranges, 3-oz. Milk Chocolate Covered Dried Strawberries, a large flower decorated sugar cookie, 3-oz. white chocolate pastel flowers, and 3-oz. Chocolate Sea Salt Caramelized Cashews.",
            "ProductImage": "http://www.ftdimg.com/pics/products/zoom/G428_600x600.jpg",
            "ThumbnailProductImage": null,
            "Price": 49.99,
            "PriceLabel": "$49.99",
            "ProductTags": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                28,
                33,
                42,
                44,
                50,
                51,
                52,
                66,
                72,
                85,
                90,
                91,
                96,
                97,
                98,
                99,
                100
            ],
            "IsTopGift": false,
            "IsPopularGift": false,
            "ProductLink": "http://www.ftd.com/easter-4-20-pcg/spring-sensation-fruit-sweets-gourmet-gift-basket/occasion-easter/4g28/?sid=1",
            "IsAffiliate": false,
            "ShippingMandatory": true,
            "PersonalMessageMaxLength": null
        },
        {
            "ProductId": 206426,
            "ProductTitle": "Godiva� Supreme",
            "Description": "A Jifiti gift will be received by the recipient as a virtual gift card which can be used to redeem the suggested gift or any other item at FTD\r\n\r\nProduct Description:\r\n\r\nSend your loving wishes in a grand way with a romantic basket filled with Godiva� chocolate! Indulge their sweet tooth with Godiva� milk chocolate and a salted caramel bar, dark chocolate covered almonds, a Godiva� solid milk chocolate and dark chocolate bar, chocolate-covered pretzels, Godiva� signature biscuits, milk chocolate-covered cashews, milk chocolate truffles, a milk chocolate and strawberry bar, a bag of dark French vanilla truffles, a bag of dark chocolate caramels and a bag of white chocolate truffles. All Godiva� and all exquisite!",
            "ProductImage": "http://www.ftdimg.com/pics/products/zoom/G884_600x600.jpg",
            "ThumbnailProductImage": null,
            "Price": 99.99,
            "PriceLabel": "$99.99",
            "ProductTags": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                28,
                29,
                30,
                31,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                90,
                91,
                92,
                93,
                96,
                97,
                98,
                99,
                100
            ],
            "IsTopGift": false,
            "IsPopularGift": false,
            "ProductLink": "http://www.ftd.com/all-gifts-pcg/godiva-supreme/product-gift-all-bestsellers/g884/?sid=1",
            "IsAffiliate": false,
            "ShippingMandatory": true,
            "PersonalMessageMaxLength": null
        },
        {
            "ProductId": 206418,
            "ProductTitle": "Happy Birthday Party Starter Ultimate Gift - VASE INCLUDED",
            "Description": "A Jifiti gift will be received by the recipient as a virtual gift card which can be used to redeem the suggested gift or any other item at FTD\r\n\r\nProduct Description:\r\n\r\nThe Happy Birthday Party Starter Ultimate Gift is a bright and beautiful way to get your special recipient set to celebrate! Bringing together an array of eye-catching gifts, this package includes an 18 stem bouquet of assorted roses in a clear glass vase, an adorable plush seated bear holiding a present that declares, \"Happy Birthday\", 15 Chocolate Dip Delights� Birthday Belgian Chocolate-Dipped Oreo� Cookies, a mylar Happy Birthday balloon, and a birthday pop-up card. Arriving in one large gift box, this ultimate gift will make their special birthday celebration one to remember.\n",
            "ProductImage": "http://www.ftdimg.com/pics/products/FW89BDAY_330x370.jpg",
            "ThumbnailProductImage": null,
            "Price": 119.99,
            "PriceLabel": "$119.99",
            "ProductTags": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                28,
                29,
                30,
                31,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                88,
                90,
                91,
                92,
                93,
                96,
                97,
                98,
                99,
                100
            ],
            "IsTopGift": true,
            "IsPopularGift": false,
            "ProductLink": "http://www.ftd.com/for-him-pcg/happy-birthday-party-starter-ultimate-gift-vase-included/product-forhim/fw89bday/?sid=1",
            "IsAffiliate": false,
            "ShippingMandatory": true,
            "PersonalMessageMaxLength": null
        },
        {
            "ProductId": 206555,
            "ProductTitle": "Tour the Wine Country Basket - Better",
            "Description": "A Jifiti gift will be received by the recipient as a virtual gift card which can be used to redeem the suggested gift or any other item at FTD\r\n\r\nProduct Description:\r\n\r\nTour the Wine Country with three delicious wines and gourmet foods. Each gift arrives with Lemon Almond Biscotti, Garlic & Herb Cheese, Spanish Olives, Beef Summer Sausage, Sweet & Hot Mustard, Nunes Farms Pistachios, Toasted Sesame Crackers and Ghirardelli Masterpiece Truffles.\nBETTER version includes Kunde Estate Zinfandel that is bold and ripe; Firestone Santa Ynez Valley Chardonnay with Fuji apple and citrus zest; Buena Vista Sonoma Cabernet Sauvignon exhibits black cherry and blueberry pie.",
            "ProductImage": "http://www.ftdimg.com/pics/products/W279_330x370.jpg",
            "ThumbnailProductImage": null,
            "Price": 149.99,
            "PriceLabel": "$149.99",
            "ProductTags": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                28,
                29,
                30,
                31,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                90,
                91,
                92,
                93,
                96,
                97,
                98,
                99,
                100
            ],
            "IsTopGift": false,
            "IsPopularGift": false,
            "ProductLink": "http://www.ftd.com/all-gifts-pcg/tour-the-wine-country/product-gift-all-bestsellers/2w02/?sid=1",
            "IsAffiliate": false,
            "ShippingMandatory": true,
            "PersonalMessageMaxLength": null
        }
    ],
    "StoreName": "FTD",
    "StoreLogo": "http://qa.jifiti.com/Images/storelogos/eviteCircles/ftd_logo.png",
    "StoreOrder": 1,
    "StoreOrder1": 1000,
    "RegularStoreLogo": "http://qa.jifiti.com/Images/storelogos/eviteRegular/ftd_logo.png",
    "IsAffiliate": null,
    "StoreText": "Put a smile on their face!",
    "HeaderImage": null,
    "BGColor": null,
    "ShippingMandatory": true,
    "PersonalMessageMaxLength": null,
    "StoreId": 1226,
    "DeliveryType": 2,
    "ShippingPolicyText": null,
    "SchedulingType": 1
}




// utilService.saveToStorage(STORES_KEY, gStores);

export const productService = {
    query,
    remove,
    save,
    getEmptyBook,
    getById,


}

async function query() {
    try {
        var products = await storageService.query(STORES_KEY);
        if (!gProducts || !products.length) products = gProducts
        return products;
    } catch (err) {
        console.log('cant load boards', err);
    }
}


function remove(storeId) {
    return storageService.remove(STORES_KEY, storeId);
}

function save(store) {
    if (store.id) {
        return storageService.put(STORES_KEY, store);
    } else {
        return storageService.post(STORES_KEY, store);
    }
}

function getById(id) {
    return storageService.get(STORES_KEY, id);
}

function getEmptyBook() {
    return {
        id: '',
        title: '',
        subtitle: '',
        authors: [],
        publishedDate: '',
        description: '',
        pageCount: '',
        categories: [],
        thumbnail: '',
        language: '',
        listPrice: {}
    }
}